sealed record CaptureReport(
    bool Ok,
    bool Usable,
    string CaptureMethod,
    string? Output,
    string? Message,
    string? ErrorType,
    string? ProcessName,
    int? Pid,
    string? TitleContains,
    string? WindowProcessName,
    int? WindowPid,
    string? WindowTitle,
    string? Hwnd,
    int Width,
    int Height,
    double BlackPixelRatio,
    double TransparentPixelRatio,
    double LumaStdDev,
    double ContentBlackPixelRatio,
    double ContentTransparentPixelRatio,
    double ContentLumaStdDev,
    QualityReport? Quality,
    bool KnownBlocker,
    string? RequestedHwnd,
    string? ExpectedProcessStartUtc,
    string? WindowProcessStartUtc,
    string? OutputRoot,
    string? Manifest,
    string? RunLog,
    string? Summary,
    string[] Warnings,
    string[] Blockers)
{
    public static CaptureReport Success(Options options, WindowMatch window, string output, QualityReport quality) => new(
        true,
        quality.Usable,
        options.CaptureMethod,
        output,
        quality.Usable ? "Captured a non-empty frame." : "Captured a frame, but pixel statistics look black/flat/transparent.",
        null,
        options.ProcessName,
        options.Pid,
        options.TitleContains,
        window.ProcessName,
        window.Pid,
        window.Title,
        $"0x{window.Hwnd.ToInt64():X}",
        quality.Width,
        quality.Height,
        quality.BlackPixelRatio,
        quality.TransparentPixelRatio,
        quality.LumaStdDev,
        quality.ContentBlackPixelRatio,
        quality.ContentTransparentPixelRatio,
        quality.ContentLumaStdDev,
        quality,
        options.RequireUsable && !quality.Usable,
        Options.FormatHwnd(options.Hwnd),
        options.ExpectedProcessStartUtc?.ToString("O"),
        window.ProcessStartUtc?.ToString("O"),
        null,
        null,
        null,
        null,
        quality.Usable ? [] : ["Captured frame quality is below usable thresholds."],
        options.RequireUsable && !quality.Usable ? ["--require-usable was specified and captured frame quality is below usable thresholds."] : []);

    public static CaptureReport Error(Options options, string message, string? errorType, WindowMatch? window = null, bool knownBlocker = true) => new(
        false,
        false,
        options.CaptureMethod,
        options.Output is null ? null : Path.GetFullPath(options.Output),
        message,
        errorType,
        options.ProcessName,
        options.Pid,
        options.TitleContains,
        window?.ProcessName,
        window?.Pid,
        window?.Title,
        window?.Hwnd == IntPtr.Zero || window is null ? null : $"0x{window.Hwnd.ToInt64():X}",
        0,
        0,
        1,
        1,
        0,
        1,
        1,
        0,
        null,
        knownBlocker,
        Options.FormatHwnd(options.Hwnd),
        options.ExpectedProcessStartUtc?.ToString("O"),
        window?.ProcessStartUtc?.ToString("O"),
        null,
        null,
        null,
        null,
        [],
        [message]);
}
