using System.Globalization;
using System.Text;
using RiftReader.Reader.AddonSnapshots;
using RiftReader.Reader.Memory;
using RiftReader.Reader.Processes;
using RiftReader.Reader.Scanning;

namespace RiftReader.Reader.CheatEngine;

public static class CheatEngineProbeScriptWriter
{
    public static CheatEngineProbeExportResult WriteProbeScript(
        ProcessMemoryReader reader,
        ProcessTarget target,
        ReaderBridgeSnapshotDocument snapshotDocument,
        int inspectionRadius,
        int maxHits,
        string outputFile)
    {
        ArgumentNullException.ThrowIfNull(reader);
        ArgumentNullException.ThrowIfNull(target);
        ArgumentNullException.ThrowIfNull(snapshotDocument);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputFile);

        var snapshot = snapshotDocument.Current ?? throw new InvalidOperationException("ReaderBridge export did not contain a current snapshot.");
        var player = snapshot.Player ?? throw new InvalidOperationException("ReaderBridge export did not contain a player snapshot.");
        var coord = player.Coord ?? throw new InvalidOperationException("ReaderBridge export did not contain player coordinates.");

        if (coord.X is not double coordX || coord.Y is not double coordY || coord.Z is not double coordZ)
        {
            throw new InvalidOperationException("ReaderBridge export did not contain a complete player coordinate triplet.");
        }

        var signatureResult = ProcessPlayerSignatureScanner.ScanReaderBridgePlayerSignature(
            reader,
            target.ProcessId,
            target.ProcessName,
            $"readerbridge-player-signature ({snapshotDocument.SourceFile})",
            (float)coordX,
            (float)coordY,
            (float)coordZ,
            player.Level,
            player.Hp,
            player.HpMax,
            player.Name,
            player.LocationName,
            inspectionRadius,
            maxHits);

        var script = BuildScript(target, snapshotDocument, player, signatureResult);
        var fullOutputFile = Path.GetFullPath(outputFile);
        var directory = Path.GetDirectoryName(fullOutputFile);

        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(fullOutputFile, script, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        return new CheatEngineProbeExportResult(
            Mode: "cheatengine-probe-export",
            ProcessId: target.ProcessId,
            ProcessName: target.ProcessName,
            OutputFile: fullOutputFile,
            ReaderBridgeSourceFile: snapshotDocument.SourceFile,
            PlayerName: player.Name,
            PlayerLevel: player.Level,
            PlayerHealth: player.Hp,
            PlayerHealthMax: player.HpMax,
            LocationName: player.LocationName,
            CoordText: FormatCoordText(coord.X, coord.Y, coord.Z),
            FamilyCount: signatureResult.FamilyCount,
            HitCount: signatureResult.HitCount,
            Families: signatureResult.Families);
    }

    private static string BuildScript(
        ProcessTarget target,
        ReaderBridgeSnapshotDocument snapshotDocument,
        ReaderBridgeUnitSnapshot player,
        PlayerSignatureScanResult signatureResult)
    {
        var builder = new StringBuilder(16 * 1024);
        var representativeHits = signatureResult.Hits.ToDictionary(static hit => hit.FamilyId, StringComparer.Ordinal);
        var generationTime = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture);

        builder.AppendLine("-- Generated by RiftReader.Reader");
        builder.AppendLine($"-- Generated at (UTC): {generationTime}");
        builder.AppendLine($"-- Process: {target.ProcessName} ({target.ProcessId})");
        builder.AppendLine($"-- ReaderBridge export: {snapshotDocument.SourceFile}");
        builder.AppendLine();
        builder.AppendLine("local ROOT_PREFIX = \"RiftReader Probe :: \"");
        builder.AppendLine();
        builder.AppendLine("local probe = {}");
        builder.AppendLine($"probe.generatedAtUtc = {ToLuaString(generationTime)}");
        builder.AppendLine($"probe.processName = {ToLuaString(target.ProcessName)}");
        builder.AppendLine($"probe.processId = {target.ProcessId}");
        builder.AppendLine($"probe.readerBridgeSourceFile = {ToLuaString(snapshotDocument.SourceFile)}");
        builder.AppendLine($"probe.searchLabel = {ToLuaString(signatureResult.SearchLabel)}");
        builder.AppendLine($"probe.inspectionRadius = {signatureResult.InspectionRadius}");
        builder.AppendLine("probe.player = {");
        builder.AppendLine($"  name = {ToLuaString(player.Name)},");
        builder.AppendLine($"  level = {ToLuaInteger(player.Level)},");
        builder.AppendLine($"  health = {ToLuaInteger(player.Hp)},");
        builder.AppendLine($"  healthMax = {ToLuaInteger(player.HpMax)},");
        builder.AppendLine($"  locationName = {ToLuaString(player.LocationName)},");
        builder.AppendLine("  coord = {");
        builder.AppendLine($"    x = {ToLuaNumber(player.Coord?.X)},");
        builder.AppendLine($"    y = {ToLuaNumber(player.Coord?.Y)},");
        builder.AppendLine($"    z = {ToLuaNumber(player.Coord?.Z)},");
        builder.AppendLine("  }");
        builder.AppendLine("}");
        builder.AppendLine("probe.families = {");

        foreach (var family in signatureResult.Families)
        {
            representativeHits.TryGetValue(family.FamilyId, out var hit);

            builder.AppendLine("  {");
            builder.AppendLine($"    familyId = {ToLuaString(family.FamilyId)},");
            builder.AppendLine($"    signature = {ToLuaString(family.Signature)},");
            builder.AppendLine($"    hitCount = {family.HitCount},");
            builder.AppendLine($"    bestScore = {family.BestScore},");
            builder.AppendLine($"    notes = {ToLuaString(family.Notes)},");
            builder.AppendLine($"    representative = {ToLuaHexAddress(ParseHexAddress(family.RepresentativeAddressHex))},");
            builder.AppendLine("    sampleAddresses = {");

            foreach (var sampleAddress in family.SampleAddresses)
            {
                builder.AppendLine($"      {ToLuaHexAddress(ParseHexAddress(sampleAddress))},");
            }

            builder.AppendLine("    },");
            builder.AppendLine("    signals = {");

            if (hit is not null)
            {
                foreach (var signal in hit.Signals)
                {
                    builder.AppendLine("      {");
                    builder.AppendLine($"        name = {ToLuaString(signal.Name)},");
                    builder.AppendLine($"        value = {ToLuaString(signal.Value)},");
                    builder.AppendLine($"        relativeOffset = {signal.RelativeOffset}");
                    builder.AppendLine("      },");
                }
            }

            builder.AppendLine("    }");
            builder.AppendLine("  },");
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("local function rr_hex(value)");
        builder.AppendLine("  return string.format(\"0x%X\", value)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_prefix(text, prefix)");
        builder.AppendLine("  if text == nil then");
        builder.AppendLine("    return false");
        builder.AppendLine("  end");
        builder.AppendLine("  return string.sub(text, 1, string.len(prefix)) == prefix");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_clear_existing()");
        builder.AppendLine("  local al = getAddressList()");
        builder.AppendLine("  for i = al.Count - 1, 0, -1 do");
        builder.AppendLine("    local rec = al[i]");
        builder.AppendLine("    if rec and rec.Parent == nil and rr_prefix(rec.Description, ROOT_PREFIX) then");
        builder.AppendLine("      rec.destroy()");
        builder.AppendLine("    end");
        builder.AppendLine("  end");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_record(parent, description, address, vartype)");
        builder.AppendLine("  local rec = getAddressList().createMemoryRecord()");
        builder.AppendLine("  rec.Description = description");
        builder.AppendLine("  rec.DontSave = true");
        builder.AppendLine("  if address ~= nil then");
        builder.AppendLine("    rec.Address = rr_hex(address)");
        builder.AppendLine("  end");
        builder.AppendLine("  if vartype ~= nil then");
        builder.AppendLine("    rec.Type = vartype");
        builder.AppendLine("  end");
        builder.AppendLine("  if parent ~= nil then");
        builder.AppendLine("    rec.appendToEntry(parent)");
        builder.AppendLine("  end");
        builder.AppendLine("  return rec");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_group(parent, description, collapsed)");
        builder.AppendLine("  local rec = rr_record(parent, description, nil, nil)");
        builder.AppendLine("  rec.IsGroupHeader = true");
        builder.AppendLine("  if collapsed ~= nil then");
        builder.AppendLine("    rec.Collapsed = collapsed");
        builder.AppendLine("  end");
        builder.AppendLine("  return rec");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_add_float(parent, description, address)");
        builder.AppendLine("  return rr_record(parent, description, address, vtSingle)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_add_dword(parent, description, address)");
        builder.AppendLine("  local rec = rr_record(parent, description, address, vtDword)");
        builder.AppendLine("  rec.ShowAsSigned = false");
        builder.AppendLine("  return rec");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_add_string(parent, description, address, size)");
        builder.AppendLine("  local rec = rr_record(parent, description, address, vtString)");
        builder.AppendLine("  rec.String.Size = size");
        builder.AppendLine("  rec.String.Unicode = false");
        builder.AppendLine("  return rec");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_add_byte_array(parent, description, address, size)");
        builder.AppendLine("  local rec = rr_record(parent, description, address, vtByteArray)");
        builder.AppendLine("  rec.Aob.Size = size");
        builder.AppendLine("  return rec");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_signal_description(signal)");
        builder.AppendLine("  local offset = string.format(\"%+d\", signal.relativeOffset)");
        builder.AppendLine("  return string.format(\"%s @ %s (expected %s)\", signal.name, offset, tostring(signal.value))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function rr_apply_family_layout(parent, baseAddress, family)");
        builder.AppendLine("  rr_add_byte_array(parent, string.format(\"context bytes @ %s\", rr_hex(baseAddress - 32)), baseAddress - 32, 96)");
        builder.AppendLine("  rr_add_float(parent, \"coord.x @ +0\", baseAddress + 0)");
        builder.AppendLine("  rr_add_float(parent, \"coord.y @ +4\", baseAddress + 4)");
        builder.AppendLine("  rr_add_float(parent, \"coord.z @ +8\", baseAddress + 8)");
        builder.AppendLine();
        builder.AppendLine("  for _, signal in ipairs(family.signals) do");
        builder.AppendLine("    if signal.name ~= \"coords\" then");
        builder.AppendLine("      local address = baseAddress + signal.relativeOffset");
        builder.AppendLine("      if signal.name == \"name\" or signal.name == \"location\" then");
        builder.AppendLine("        local expected = tostring(signal.value or \"\")");
        builder.AppendLine("        local size = math.max(#expected + 16, 32)");
        builder.AppendLine("        rr_add_string(parent, rr_signal_description(signal), address, size)");
        builder.AppendLine("      else");
        builder.AppendLine("        rr_add_dword(parent, rr_signal_description(signal), address)");
        builder.AppendLine("      end");
        builder.AppendLine("    end");
        builder.AppendLine("  end");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("function probe.attach()");
        builder.AppendLine("  local pid = getProcessIDFromProcessName(probe.processName)");
        builder.AppendLine("  if pid == nil or pid == 0 then");
        builder.AppendLine("    print(string.format(\"[RiftReader] Could not find process '%s'.\", tostring(probe.processName)))");
        builder.AppendLine("    return false");
        builder.AppendLine("  end");
        builder.AppendLine();
        builder.AppendLine("  openProcess(pid)");
        builder.AppendLine("  print(string.format(\"[RiftReader] Attached to %s (PID %d).\", tostring(probe.processName), pid))");
        builder.AppendLine("  return true");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("function probe.clear()");
        builder.AppendLine("  rr_clear_existing()");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("function probe.showSummary()");
        builder.AppendLine("  print(string.format(\"[RiftReader] Player: %s\", tostring(probe.player.name or \"n/a\")))");
        builder.AppendLine("  print(string.format(\"[RiftReader] Level: %s\", tostring(probe.player.level or \"n/a\")))");
        builder.AppendLine("  print(string.format(\"[RiftReader] Health: %s/%s\", tostring(probe.player.health or \"n/a\"), tostring(probe.player.healthMax or \"n/a\")))");
        builder.AppendLine("  print(string.format(\"[RiftReader] Location: %s\", tostring(probe.player.locationName or \"n/a\")))");
        builder.AppendLine("  if probe.player.coord then");
        builder.AppendLine("    print(string.format(\"[RiftReader] Coords: %.5f, %.5f, %.5f\", probe.player.coord.x or 0, probe.player.coord.y or 0, probe.player.coord.z or 0))");
        builder.AppendLine("  end");
        builder.AppendLine("  print(string.format(\"[RiftReader] Candidate families: %d\", #probe.families))");
        builder.AppendLine("  for _, family in ipairs(probe.families) do");
        builder.AppendLine("    print(string.format(\"[RiftReader]   %s | hits=%d | score=%d | rep=%s | %s\", family.familyId, family.hitCount, family.bestScore, rr_hex(family.representative), tostring(family.notes or \"\")))");
        builder.AppendLine("  end");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("function probe.populate()");
        builder.AppendLine("  rr_clear_existing()");
        builder.AppendLine();
        builder.AppendLine("  local root = rr_group(nil, ROOT_PREFIX .. tostring(probe.player.name or \"player\"), false)");
        builder.AppendLine("  rr_group(root, ROOT_PREFIX .. string.format(\"snapshot :: %s Lv%s :: %s\", tostring(probe.player.name or \"n/a\"), tostring(probe.player.level or \"n/a\"), tostring(probe.player.locationName or \"n/a\")), true)");
        builder.AppendLine();
        builder.AppendLine("  for _, family in ipairs(probe.families) do");
        builder.AppendLine("    local familyGroup = rr_group(root, ROOT_PREFIX .. string.format(\"%s :: hits=%d :: score=%d :: %s\", family.familyId, family.hitCount, family.bestScore, tostring(family.notes or \"\")), true)");
        builder.AppendLine("    for sampleIndex, sampleAddress in ipairs(family.sampleAddresses) do");
        builder.AppendLine("      local label = string.format(\"sample %d :: %s\", sampleIndex, rr_hex(sampleAddress))");
        builder.AppendLine("      if sampleAddress == family.representative then");
        builder.AppendLine("        label = label .. \" :: representative\"");
        builder.AppendLine("      end");
        builder.AppendLine("      local sampleGroup = rr_group(familyGroup, ROOT_PREFIX .. label, true)");
        builder.AppendLine("      rr_apply_family_layout(sampleGroup, sampleAddress, family)");
        builder.AppendLine("    end");
        builder.AppendLine("  end");
        builder.AppendLine();
        builder.AppendLine("  print(string.format(\"[RiftReader] Populated %d family groups into the Cheat Engine address list.\", #probe.families))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("function probe.attachAndPopulate()");
        builder.AppendLine("  if probe.attach() then");
        builder.AppendLine("    probe.populate()");
        builder.AppendLine("    return true");
        builder.AppendLine("  end");
        builder.AppendLine("  return false");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("RiftReaderProbe = probe");
        builder.AppendLine("print(\"[RiftReader] Cheat Engine probe loaded.\")");
        builder.AppendLine("probe.showSummary()");
        builder.AppendLine("print(\"[RiftReader] Run RiftReaderProbe.attachAndPopulate() to attach and add probe records.\")");
        builder.AppendLine();
        builder.AppendLine("return probe");

        return builder.ToString();
    }

    private static string? FormatCoordText(double? x, double? y, double? z)
    {
        if (x is null || y is null || z is null)
        {
            return null;
        }

        return string.Create(CultureInfo.InvariantCulture, $"{x.Value:G9}, {y.Value:G9}, {z.Value:G9}");
    }

    private static long ParseHexAddress(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new InvalidOperationException("Cheat Engine probe generation encountered an empty sample address.");
        }

        var normalized = value.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
            ? value[2..]
            : value;

        return long.Parse(normalized, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
    }

    private static string ToLuaString(string? value)
    {
        if (value is null)
        {
            return "nil";
        }

        var builder = new StringBuilder(value.Length + 8);
        builder.Append('"');

        foreach (var character in value)
        {
            builder.Append(character switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => character.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string ToLuaInteger(int? value) =>
        value.HasValue
            ? value.Value.ToString(CultureInfo.InvariantCulture)
            : "nil";

    private static string ToLuaInteger(long? value) =>
        value.HasValue
            ? value.Value.ToString(CultureInfo.InvariantCulture)
            : "nil";

    private static string ToLuaNumber(double? value) =>
        value.HasValue
            ? value.Value.ToString("G17", CultureInfo.InvariantCulture)
            : "nil";

    private static string ToLuaHexAddress(long value) =>
        $"0x{value:X}";
}
