namespace RiftReader.Reader.AddonSnapshots;

public sealed record ReaderBridgeSnapshot(
    int? SchemaVersion,
    string? Status,
    string? ExportReason,
    int? ExportCount,
    double? GeneratedAtRealtime,
    string? SourceMode,
    string? SourceAddon,
    string? SourceVersion,
    string? ExportAddon,
    string? ExportVersion,
    string? PlayerId,
    string? TargetId,
    ReaderBridgeHudSnapshot? Hud,
    ReaderBridgeUnitSnapshot? Player,
    ReaderBridgeUnitSnapshot? Target,
    ReaderBridgeOrientationProbeSnapshot? OrientationProbe,
    IReadOnlyDictionary<string, double> PlayerStats,
    ReaderBridgeCoordinateDeltaSnapshot? PlayerCoordDelta,
    ReaderBridgeUnitCollectionSummarySnapshot? NearbySummary,
    ReaderBridgeUnitCollectionSummarySnapshot? PartySummary,
    IReadOnlyList<ReaderBridgeUnitSnapshot> NearbyUnits,
    IReadOnlyList<ReaderBridgeUnitSnapshot> PartyUnits,
    IReadOnlyList<string> PlayerBuffLines,
    IReadOnlyList<string> PlayerDebuffLines,
    IReadOnlyList<string> TargetBuffLines,
    IReadOnlyList<string> TargetDebuffLines,
    IReadOnlyList<ReaderBridgeBuffSnapshot> PlayerBuffs,
    IReadOnlyList<ReaderBridgeBuffSnapshot> PlayerDebuffs,
    IReadOnlyList<ReaderBridgeBuffSnapshot> TargetBuffs,
    IReadOnlyList<ReaderBridgeBuffSnapshot> TargetDebuffs);
