@echo off
setlocal EnableExtensions

for %%I in ("%~dp0..") do set "REPO_ROOT=%%~fI"

if defined CHEAT_ENGINE_DIR (
    set "CE_ROOT=%CHEAT_ENGINE_DIR%"
) else (
    set "CE_ROOT=C:\Program Files\Cheat Engine"
)

set "CUSTOM_DIR=%CE_ROOT%\autorun\custom"
set "BOOTSTRAP_FILE=%CUSTOM_DIR%\RiftReaderBootstrap.lua"
set "PROBE_FILE=%REPO_ROOT%\scripts\cheat-engine\RiftReaderProbe.lua"

if not exist "%CUSTOM_DIR%" (
    mkdir "%CUSTOM_DIR%" || (
        echo Failed to create Cheat Engine autorun folder: %CUSTOM_DIR%
        exit /b 1
    )
)

> "%BOOTSTRAP_FILE%" (
    echo -- Auto-generated by RiftReader
    echo local scriptPath = [[%PROBE_FILE%]]
    echo local ok, result = pcall(dofile, scriptPath^)
    echo if not ok then
    echo   print(string.format("[RiftReader] Failed to load probe script '%%s': %%s", scriptPath, tostring(result^)^)^)
    echo end
)

echo Installed Cheat Engine autorun bootstrap:
echo   %BOOTSTRAP_FILE%
echo It will load:
echo   %PROBE_FILE%
exit /b 0
