using RiftReader.Reader.Scanning;

namespace RiftReader.Reader.Cli;

public sealed record ReaderOptions(
    int? ProcessId,
    string? ProcessName,
    nint? Address,
    int? Length,
    bool ListModules,
    string? ScanModuleName,
    string? ScanModulePattern,
    bool WriteCheatEngineProbe,
    string? CheatEngineProbeFile,
    bool RankOwnerComponents,
    string? OwnerComponentsFile,
    bool RankStatHubs,
    bool CheatEngineStatHubs,
    bool ReadPlayerOrientation,
    bool CaptureReaderBridgeBestFamily,
    bool ReadPlayerCurrent,
    bool ReadPlayerCoordAnchor,
    bool ReadTargetCurrent,
    bool SessionSummary,
    string? SessionDirectory,
    bool RecordSession,
    string? SessionWatchsetFile,
    string? SessionOutputDirectory,
    string? SessionMarkerInputFile,
    int SessionSampleCount,
    int SessionIntervalMilliseconds,
    string? SessionLabel,
    string? PlayerCoordTraceFile,
    string? CaptureLabel,
    string? CaptureFile,
    string? ScanString,
    nint? ScanPointer,
    int? ScanInt32,
    float? ScanFloat,
    double? ScanDouble,
    double ScanTolerance,
    int PointerWidth,
    StringScanEncoding ScanEncoding,
    int ScanContextBytes,
    int MaxHits,
    bool ScanReaderBridgePlayerName,
    bool ScanReaderBridgePlayerCoords,
    bool ScanReaderBridgePlayerSignature,
    bool ScanReaderBridgePlayerSourceChain,
    bool ScanReaderBridgeIdentity,
    bool ReadAddonSnapshot,
    string? AddonSnapshotFile,
    bool ReadReaderBridgeSnapshot,
    string? ReaderBridgeSnapshotFile,
    bool JsonOutput,
    bool FindPlayerOrientationCandidate = false,
    string? OrientationCandidateLedgerFile = null,
    bool DebugTraceInstruction = false,
    bool DebugTraceMemoryWrite = false,
    bool DebugTraceMemoryAccess = false,
    bool DebugTracePlayerCoordWrite = false,
    bool DebugTraceSummary = false,
    string? DebugTraceDirectory = null,
    nint? DebugAddress = null,
    string? DebugModuleName = null,
    nint? DebugModuleOffset = null,
    int? DebugWidth = null,
    int DebugTimeoutMilliseconds = 8000,
    int DebugMaxHits = 8,
    int DebugMaxEvents = 5000,
    string? DebugOutputDirectory = null,
    int DebugCaptureStackBytes = 256,
    int DebugCaptureMemoryWindowBytes = 128,
    string? DebugMarkerInputFile = null,
    string? DebugLabel = null,
    bool DebugDisableRegisterCapture = false,
    bool DebugDisableStackCapture = false,
    bool DebugDisableMemoryWindows = false,
    bool DebugDisableInstructionDecode = false,
    bool DebugDisableInstructionFingerprint = false,
    bool DebugDisableHitClustering = false,
    bool DebugDisableFollowUpSuggestions = false,
    bool DebugWorker = false,
    string? DebugRequestFile = null);
