using RiftReader.Reader.Scanning;

namespace RiftReader.Reader.Cli;

public sealed record ReaderOptions(
    int? ProcessId,
    string? ProcessName,
    nint? Address,
    int? Length,
    bool ListModules,
    string? ScanModuleName,
    string? ScanModulePattern,
    bool WriteCheatEngineProbe,
    string? CheatEngineProbeFile,
    bool RankOwnerComponents,
    string? OwnerComponentsFile,
    bool RankStatHubs,
    bool CheatEngineStatHubs,
    bool ReadPlayerOrientation,
    bool CaptureReaderBridgeBestFamily,
    bool ReadPlayerCurrent,
    bool ReadPlayerCoordAnchor,
    bool ReadTargetCurrent,
    bool SessionSummary,
    string? SessionDirectory,
    bool RecordSession,
    string? SessionWatchsetFile,
    string? SessionOutputDirectory,
    string? SessionMarkerInputFile,
    int SessionSampleCount,
    int SessionIntervalMilliseconds,
    string? SessionLabel,
    string? PlayerCoordTraceFile,
    string? CaptureLabel,
    string? CaptureFile,
    string? ScanString,
    nint? ScanPointer,
    int? ScanInt32,
    float? ScanFloat,
    double? ScanDouble,
    FloatTripletScanValues? ScanFloatTriplet,
    double ScanTolerance,
    int PointerWidth,
    StringScanEncoding ScanEncoding,
    int ScanContextBytes,
    int MaxHits,
    bool ScanReaderBridgePlayerName,
    bool ScanReaderBridgePlayerCoords,
    bool ScanReaderBridgePlayerSignature,
    bool ScanReaderBridgeIdentity,
    bool ReadAddonSnapshot,
    string? AddonSnapshotFile,
    bool ReadReaderBridgeSnapshot,
    string? ReaderBridgeSnapshotFile,
    bool JsonOutput,
    bool FindPlayerOrientationCandidate = false,
    string? OrientationCandidateLedgerFile = null,
    bool ReadNavigationCurrent = false,
    bool PlanNavigationRoute = false,
    bool NavigateWaypointRoute = false,
    bool NavigateWaypoints = false,
    string? NavigationWaypointFile = null,
    string? StartWaypointId = null,
    IReadOnlyList<string>? ViaWaypointIds = null,
    string? DestinationWaypointId = null,
    string? Pace = null,
    double? ArrivalRadius = null,
    int? MaxTravelSeconds = null,
    bool AutoTurnBeforeMove = false,
    double? AutoTurnWithinDegrees = null,
    string? TurnLeftKey = null,
    string? TurnRightKey = null,
    int? TurnPulseMilliseconds = null,
    int? TurnPostSampleDelayMilliseconds = null,
    int? TurnSettleDelayMilliseconds = null,
    int? TurnMaxPulses = null,
    double? TurnWorseningToleranceDegrees = null,
    int? TurnMaxWorseningPulses = null,
    bool CaptureNavigationWaypoint = false,
    string? CaptureNavigationWaypointId = null,
    string? WaypointLabel = null,
    string? WaypointZone = null,
    double? WaypointArrivalRadius = null,
    string? WaypointPace = null,
    bool TelemetryPreflight = false,
    bool RunTelemetryHost = false,
    int TelemetryPollIntervalMilliseconds = 100,
    bool TelemetryDiagnostics = false,
    string? TelemetryOutputFile = null,
    string? TelemetryEventLogFile = null,
    string? TelemetryDiagnosticsLogFile = null,
    string? TelemetryProofAnchorFile = null,
    bool VerboseNavigationEvents = false,
    bool ImportTomTomWaypoints = false,
    string? TomTomSavedVariablesFile = null,
    IReadOnlyList<string>? TomTomListNames = null,
    string? TomTomZone = null,
    double? TomTomDefaultY = null,
    string? TomTomIdPrefix = null,
    double? TomTomArrivalRadius = null,
    string? TomTomPace = null,
    string? NavigationRunSummaryFile = null);

public sealed record FloatTripletScanValues(
    float First,
    float Second,
    float Third);
