using RiftReader.Reader.Scanning;

namespace RiftReader.Reader.Cli;

public sealed record ReaderOptions(
    int? ProcessId,
    string? ProcessName,
    nint? Address,
    int? Length,
    bool ListModules,
    string? ScanModuleName,
    string? ScanModulePattern,
    bool WriteCheatEngineProbe,
    string? CheatEngineProbeFile,
    bool RankOwnerComponents,
    string? OwnerComponentsFile,
    bool RankStatHubs,
    bool CheatEngineStatHubs,
    bool ReadPlayerOrientation,
    bool CaptureReaderBridgeBestFamily,
    bool ReadPlayerCurrent,
    bool ReadPlayerCoordAnchor,
    bool ReadTargetCurrent,
    bool SessionSummary,
    string? SessionDirectory,
    bool RecordSession,
    string? SessionWatchsetFile,
    string? SessionOutputDirectory,
    string? SessionMarkerInputFile,
    int SessionSampleCount,
    int SessionIntervalMilliseconds,
    string? SessionLabel,
    string? PlayerCoordTraceFile,
    string? CaptureLabel,
    string? CaptureFile,
    string? ScanString,
    nint? ScanPointer,
    int? ScanInt32,
    float? ScanFloat,
    double? ScanDouble,
    double ScanTolerance,
    int PointerWidth,
    StringScanEncoding ScanEncoding,
    int ScanContextBytes,
    int MaxHits,
    bool ScanReaderBridgePlayerName,
    bool ScanReaderBridgePlayerCoords,
    bool ScanReaderBridgePlayerSignature,
    bool ScanReaderBridgeIdentity,
    bool ReadAddonSnapshot,
    string? AddonSnapshotFile,
    bool ReadReaderBridgeSnapshot,
    string? ReaderBridgeSnapshotFile,
    bool JsonOutput,
    bool ReadNavigationCurrent = false,
    bool NavigateWaypoints = false,
    string? NavigationWaypointFile = null,
    string? StartWaypointId = null,
    string? DestinationWaypointId = null,
    string? Pace = null,
    double? ArrivalRadius = null,
    int? MaxTravelSeconds = null,
    bool CaptureNavigationWaypoint = false,
    string? CaptureNavigationWaypointId = null,
    string? WaypointLabel = null,
    string? WaypointZone = null,
    double? WaypointArrivalRadius = null,
    string? WaypointPace = null);
